_target_: src.optimization.lr_scheduler.LinearWarmupCosineAnnealingLR
warmup_steps: 1000
max_epochs: ${trainer.max_epochs}   # Specify either OR
max_steps: ${trainer.max_steps}
warmup_start_lr: 1e-8
eta_min: 1e-8
last_epoch: -1
interval: "step"
